service: gm-graphql

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  profile: gm

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    playersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gm-players-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
 
