service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    playersTable:
      Type: AWS::DynamoDB:Table
      Properties:
        TableName: gm-players-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttibuteName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
 
